### PR TITLE
fix for AlleleListUtilsUnitTest

### LINKED ISSUE #607: Refactor AlleleListUtilsUnitTest to have no skips and be robustly deterministic
There are a number of skipped tests on a successful run of `AlleleListUtilsUnitTest`  These are deliberately skipped because the tests share a single data provider, but each test can only use a subset of the data.  These should be refactored to avoid skipping tests.

These tests also make use of random number generators.  It looks like these may not be properly isolated and may introduce coupling between what should be independent tests.

### PR DESCRIPTION
**Pull request by akiezun**
fixes #607 

@lbergelson please review

### CODE REVIEW

File: src/test/java/org/broadinstitute/hellbender/utils/genotyper/AlleleListUtilsUnitTest.java [hunk 1]
```diff
@@ -107,41 +129,44 @@ public void testSelfPermutation(final List<Allele> alleles1) {
...
+        Assert.assertTrue(AlleleListUtils.equals(subset, targetRandomAlleleList));
     }
 
     @Test(dataProvider = "singleAlleleListData", dependsOnMethods = {"testAsList","testEquals"})
     public void testShufflePermutation(final List<Allele> alleles1) {
         final AlleleList<Allele> originalAlleleList = new IndexedAlleleList<>(alleles1);
-        if (originalAlleleList.alleleCount() <= 1)
-            throw new SkipException("non-shuffle allele-list");
+        if (originalAlleleList.alleleCount() <= 1) {
+            return; //just return, no skip so that it doesnt polute build logs
```
Comment (lbergelson) [inline src/test/java/org/broadinstitute/hellbender/utils/genotyper/AlleleListUtilsUnitTest.java]: typo:  pol**l**ute

Comment (lbergelson) [inline src/test/java/org/broadinstitute/hellbender/utils/genotyper/AlleleListUtilsUnitTest.java]: actually, lets just change this comment to something like

 "return because this input is invalid for this test"

File: src/test/java/org/broadinstitute/hellbender/utils/genotyper/AlleleListUtilsUnitTest.java [hunk 2]
```diff
@@ -107,41 +129,44 @@ public void testSelfPermutation(final List<Allele> alleles1) {
...
+        }
         final AlleleList<Allele> originalAlleleList = new IndexedAlleleList<>(alleles1);
-        final AlleleList<Allele> targetAlleleList = new IndexedAlleleList<>(subsetAlleles);
-        final AlleleListPermutation<Allele> subset = AlleleListUtils.permutation(originalAlleleList,targetAlleleList);
-        if (originalAlleleList.alleleCount() == targetAlleleList.alleleCount())
-            throw new SkipException("no real subset");
+        final AlleleList<Allele> targetRandomAlleleList = new IndexedAlleleList<>(randomSubsetAlleles);
+        final AlleleListPermutation<Allele> subset = AlleleListUtils.permutation(originalAlleleList,targetRandomAlleleList);
+        if (originalAlleleList.alleleCount() == targetRandomAlleleList.alleleCount()) {
+            return;//just return, no skip so that it doesnt polute build logs
```
Comment (lbergelson) [inline src/test/java/org/broadinstitute/hellbender/utils/genotyper/AlleleListUtilsUnitTest.java]: same comment as below

**Comment by lbergelson** [comment]
:+1:  Thanks for fixing this.  Just the comment on the comment.  Feel free to merge when that is updated.

I do think this test class is still very confusing in general though. 

I don't understand why it's testing on a random combinatorial set of inputs instead of choosing a few explicitly.  Surely showing that a method throws on null input once is just as good as showing it 10 time. Refactoring the whole thing seems out of scope though.

**Comment by lbergelson** [comment]
@akiezun back to you

File: src/test/java/org/broadinstitute/hellbender/utils/genotyper/AlleleListUtilsUnitTest.java (hunk 1 above)
Comment (akiezun) [inline src/test/java/org/broadinstitute/hellbender/utils/genotyper/AlleleListUtilsUnitTest.java]: done

File: src/test/java/org/broadinstitute/hellbender/utils/genotyper/AlleleListUtilsUnitTest.java (hunk 2 above)
Comment (akiezun) [inline src/test/java/org/broadinstitute/hellbender/utils/genotyper/AlleleListUtilsUnitTest.java]: done
