### PR TITLE
Working on a fix

### LINKED ISSUE #802: Ensure that reference sequence dictionary always contains all contigs from reads/variants sequence dictionaries
Currently we check only that sequence dictionaries have a common subset of equal contigs. When comparing against the reference sequence dictionary, however, we need to check that the ref dictionary contains all contigs from the reads/variants dictionaries. If this is not the case, we can see null pointer exceptions with cram files and other nasty errors.

### PR DESCRIPTION
**Pull request by edwardkw**
Fixes #802. Unit tests fixed/added.

### CODE REVIEW

File: src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java [hunk 1]
```diff
@@ -108,6 +108,34 @@ private boolean hasCramInput() {
...
+    private List<File> cramInputFiles() {
+        ArrayList<File> cramFiles = new ArrayList<>();
+        for (File inputFile : readArguments.getReadFiles()) {
+            if (FilenameUtils.getExtension(inputFile.getName()).equalsIgnoreCase("cram")) {
+                cramFiles.add(inputFile);
+            }
+        }
+        return cramFiles;
+    } */
+
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java]: Remove this huge block of commented-out code

File: src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java [hunk 2]
```diff
@@ -50,9 +50,11 @@
     public enum SequenceDictionaryCompatibility {
         IDENTICAL,                      // the dictionaries are identical
         COMMON_SUBSET,                  // there exists a common subset of equivalent contigs
+        TWO_SUPERSETS_ONE,               // the second dict's set of contigs is a superset of the first dict's; used
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java]: This name is pretty awkward -- recommend just calling this `SUPERSET`

Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java]: Also, this comment looks incomplete (has a stray "; used" at the end)

File: src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java [hunk 3]
```diff
@@ -293,10 +321,10 @@ private void validateSequenceDictionaries() {
         //check reference dict against reads dict
         if (hasReference() && hasReads()) {
             if (hasIntervals()){
-                SequenceDictionaryUtils.validateDictionaries("reference", refDict, "reads", readDict, true, intervalsForTraversal);
+                SequenceDictionaryUtils.validateDictionaries("reads", readDict, "reference", refDict, true, intervalsForTraversal);
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/engine/GATKTool.java]: I think the reference dictionary was better as the first parameter -- it seems more logical to say that the first thing is a superset of the second, rather than the other way around.

File: src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java [hunk 4]
```diff
@@ -176,11 +183,30 @@ else if ( commonContigs.size() == dict1.size() && commonContigs.size() == dict2.
...
+     *
+     * @param commonContigs
+     * @param dict1
+     * @param dict2
+     * @return true if dict2's set of contigs supersets dict1's
+     */
+    private static boolean twoSupersetsOne(Set<String> commonContigs, SAMSequenceDictionary dict1, SAMSequenceDictionary dict2) {
+        Set<String> nameSetOne = getContigNames(dict1);
+        Set<String> nameSetTwo = getContigNames(dict2);
+        return nameSetTwo.containsAll(nameSetOne);
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java]: This check is not quite sufficient -- you want to make sure that the reference dictionary contains all the contigs from the reads **with the same length for each contig**. Easiest thing to do is to make these a `Set<SAMSequenceRecord>` -- you can get the `SAMSequenceRecords` out of each `SAMSequenceDictionary` via the `getSequences()` method.

File: src/test/java/org/broadinstitute/hellbender/engine/CRAMReferenceIntegrationTest.java [hunk 5]
```diff
@@ -59,7 +59,7 @@ public void testNoRefMulti(String fileIn1, String fileIn2, String extOut) throws
         };
     }
 // TODO: re-enable this test once wrong ref situation is fixed #793
-    /*@Test(dataProvider="testingDataWrongRef", expectedExceptions = UserException.class)
+    @Test(dataProvider="testingDataWrongRef", expectedExceptions = UserException.class)
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/engine/CRAMReferenceIntegrationTest.java]: `UserException.IncompatibleSequenceDictionaries`?

File: src/test/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtilsUnitTest.java [hunk 6]
```diff
@@ -115,6 +113,13 @@
...
                 { Arrays.asList(CHR1_HG19, CHR_NONSTANDARD1, CHR2_HG19, CHRM_HG19), Arrays.asList(CHR1_HG19, CHR2_HG19, CHRM_HG19), DIFFERENT_INDICES, null, false, hg19AllContigsIntervalSet },
+
+                // tests for TWO_SUPERSETS_ONE
+
+                { Arrays.asList(CHR1_HG19),                                          Arrays.asList(CHR1_HG19, CHR2_HG19),                                          TWO_SUPERSETS_ONE, null, true, hg19AllContigsIntervalSet },
+                { Arrays.asList(CHR1_HG19),                                          Arrays.asList(CHR1_HG19, CHR_NONSTANDARD1),                                   TWO_SUPERSETS_ONE, null, false, null },
+                { Arrays.asList(CHR1_HG19, CHR2_HG19),                               Arrays.asList(CHR1_HG19, CHR2_HG19, CHR10_HG19),                              TWO_SUPERSETS_ONE, null, false, null },
+                { Arrays.asList(CHR1_HG19, CHR2_HG19, CHR10_HG19),                   Arrays.asList(CHR1_HG19, CHR2_HG19, CHR10_HG19, CHR_NONSTANDARD1),            TWO_SUPERSETS_ONE, null, false, null },
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtilsUnitTest.java]: Add a test case for same contig name but different lengths

File: src/test/resources/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils/test.dict [hunk 7]
```diff
@@ -1,5 +1,9 @@
...
 @SQ	SN:3	LN:16000	M5:94de808a3a2203dbb02434a47bd8184f	UR:file:/Users/edwardk/Documents/hellbender/src/test/resources/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils/test.fasta
 @SQ	SN:4	LN:16000	M5:7d397ee919e379328d8f52c57a54c778	UR:file:/Users/edwardk/Documents/hellbender/src/test/resources/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils/test.fasta
+@SQ	SN:chr5	LN:101	M5:ae947e7425533fdc9db7535ce21a897a	UR:file:/Users/edwardk/Documents/hellbender/src/test/resources/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils/test.fasta
+@SQ	SN:chr6	LN:101	M5:ec55306bb0c635adae21c7733b9db6ab	UR:file:/Users/edwardk/Documents/hellbender/src/test/resources/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils/test.fasta
+@SQ	SN:chr7	LN:404	M5:cddcca887c75987e49ab3b7e418ce283	UR:file:/Users/edwardk/Documents/hellbender/src/test/resources/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils/test.fasta
+@SQ	SN:chr8	LN:202	M5:95467d3917cd8bcb824dc586b0384079	UR:file:/Users/edwardk/Documents/hellbender/src/test/resources/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils/test.fasta
```
Comment (droazen) [inline src/test/resources/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils/test.dict]: Don't mix `1` and `chr5` style names in the same sequence dictionary

File: src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java [hunk 8]
```diff
@@ -87,6 +89,11 @@ public static void validateDictionaries( final String name1,
             case IDENTICAL:
                 return;
             case COMMON_SUBSET:
+                if (isReadsToReferenceComparison) {
+                    throw new UserException.IncompatibleSequenceDictionaries("Reference is missing contigs found in reads", name1, dict1, name2, dict2);
+                }
+                return;
+            case TWO_SUPERSETS_ONE:
                 return;
             case NO_COMMON_CONTIGS:
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java]: You need to make sure that if we get `DIFFERENT_INDICES` and we're in a reads to reference comparison, we always throw (since we want to require `IDENTICAL` or `SUPERSET` for reads + ref comparisons now.

**Comment by droazen** [comment]
First-pass review complete -- back to @edwardkw

File: src/test/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtilsUnitTest.java (hunk 6 above)
Comment (edwardkw) [inline src/test/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtilsUnitTest.java]: The test cases for UNEQUAL_COMMON_CONTIGS cover this.

File: src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java [hunk 9]
```diff
@@ -176,11 +188,30 @@ else if ( commonContigs.size() == dict1.size() && commonContigs.size() == dict2.
...
+     * Utility function that tests whether dict2's set of contigs supersets dict1's
+     *
+     * @param commonContigs
+     * @param dict1
+     * @param dict2
+     * @return true if dict2's set of contigs supersets dict1's
+     */
+    private static boolean supersets(Set<String> commonContigs, SAMSequenceDictionary dict1, SAMSequenceDictionary dict2) {
+        Set<SAMSequenceRecord> setOne = (Set<SAMSequenceRecord>) dict1.getSequences();
+        Set<SAMSequenceRecord> setTwo = (Set<SAMSequenceRecord>) dict2.getSequences();
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java]: Your tests are failing in this branch because you can't typecast a `List` (which is what `getSequences()` returns) to a `Set`. If you want to convert from `List` to `Set` you have to call a constructor -- eg., `new HashSet<>(dict1.getSequences())`.

File: src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java [hunk 10]
```diff
@@ -50,9 +50,11 @@
     public enum SequenceDictionaryCompatibility {
         IDENTICAL,                      // the dictionaries are identical
         COMMON_SUBSET,                  // there exists a common subset of equivalent contigs
+        SUPERSETS,               // the second dict's set of contigs is a superset of the first dict's; used
+        // specifically with reference and reads
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java]: Update the comment here -- "the first dict's set of contigs is a superset of the second dict's", and remove note about "used specifically with reference and reads", since that may change in the future

Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java]: Should also use the singular `SUPERSET` here for consistency with the other existing enum values (eg., `COMMON_SUBSET`)

File: src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java [hunk 11]
```diff
@@ -176,11 +188,30 @@ else if ( commonContigs.size() == dict1.size() && commonContigs.size() == dict2.
...
+     *
+     * @param commonContigs
+     * @param dict1
+     * @param dict2
+     * @return true if dict2's set of contigs supersets dict1's
+     */
+    private static boolean supersets(Set<String> commonContigs, SAMSequenceDictionary dict1, SAMSequenceDictionary dict2) {
+        Set<SAMSequenceRecord> setOne = (Set<SAMSequenceRecord>) dict1.getSequences();
+        Set<SAMSequenceRecord> setTwo = (Set<SAMSequenceRecord>) dict2.getSequences();
+        return setOne.containsAll(setTwo) && commonContigsHaveSameLengths(commonContigs, dict1, dict2);
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java]: You don't need to call `commonContigsHaveSameLengths()` here, since the `containsAll()` call will invoke `equals()` on the `SAMSequenceRecord` objects, which will check both the names and the lengths.

File: src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java [hunk 12]
```diff
@@ -176,11 +188,30 @@ else if ( commonContigs.size() == dict1.size() && commonContigs.size() == dict2.
...
     }
 
+
+    /**
+     * Utility function that tests whether dict2's set of contigs supersets dict1's
+     *
+     * @param commonContigs
+     * @param dict1
+     * @param dict2
+     * @return true if dict2's set of contigs supersets dict1's
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java]: Comment is backwards (dict1 supersets dict2)

File: src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java [hunk 13]
```diff
@@ -176,11 +188,30 @@ else if ( commonContigs.size() == dict1.size() && commonContigs.size() == dict2.
...
+        else if ( supersets(commonContigs, dict1, dict2))
+            return SequenceDictionaryCompatibility.SUPERSETS;
         else {
             return SequenceDictionaryCompatibility.COMMON_SUBSET;
         }
     }
 
+
+    /**
+     * Utility function that tests whether dict2's set of contigs supersets dict1's
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java]: Comment is backwards (dict1 supersets dict2)

File: src/test/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtilsUnitTest.java [hunk 14]
```diff
@@ -115,6 +114,12 @@
                 // These have isReadsToReferenceComparison == false, so we don't expect an exception:
                 { Arrays.asList(CHRM_HG19, CHR1_HG19),                              Arrays.asList(CHR1_HG19),                       DIFFERENT_INDICES, null, false, hg19AllContigsIntervalSet },
                 { Arrays.asList(CHR1_HG19, CHR_NONSTANDARD1, CHR2_HG19, CHRM_HG19), Arrays.asList(CHR1_HG19, CHR2_HG19, CHRM_HG19), DIFFERENT_INDICES, null, false, hg19AllContigsIntervalSet },
+
+                // tests for SUPERSETS
+
+                { Arrays.asList(CHR1_HG19, CHR2_HG19),                                  Arrays.asList(CHR1_HG19),                                                       SUPERSETS, null, true, hg19AllContigsIntervalSet },
+                { Arrays.asList(CHR1_HG19, CHR_NONSTANDARD1),                           Arrays.asList(CHR1_HG19),                                                       SUPERSETS, null, true, null },
+                { Arrays.asList(CHR1_HG19, CHR2_HG19, CHR10_HG19, CHR_NONSTANDARD1),    Arrays.asList(CHR1_HG19, CHR2_HG19, CHR10_HG19),                                SUPERSETS, null, false, null },
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtilsUnitTest.java]: Branch is not compiling because you didn't change `SUPERSETS` -> `SUPERSET` here

File: src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java [hunk 15]
```diff
@@ -126,24 +132,29 @@ public static void validateDictionaries( final String name1,
...
+                                    "the reference: %s.  As a result, the GATK engine will not correctly " +
+                                    "process reads from these contigs. You should either fix the sequence " +
+                                    "dictionaries for your reads so that these contigs have the same indices " +
+                                    "as in the sequence dictionary for your reference, or exclude these contigs " +
+                                    "from your intervals.";
+                            final UserException ex = new UserException.IncompatibleSequenceDictionaries(msg, name1, dict1, name2, dict2);
+                            throw ex;
+                        }
+                    } else {
+                        throw new UserException.IncompatibleSequenceDictionaries("Reference is missing contigs found in reads", name1, dict1, name2, dict2);
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java]: This error message isn't right -- the reference isn't necessarily missing contigs found in the reads, there are just common contigs that have different indices.

Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java]: Actually, let's change this block of code so that we always throw if we get `DIFFERENT_INDICES` and `isReadsToReferenceComparison` is true (if it proves too annoying/restrictive, we can relax it later). This also means that you can remove the intervals argument to this method.

File: src/test/resources/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils/test.fasta.fai [hunk 16]
```diff
@@ -2,3 +2,7 @@
 2	16000	16296	80	81
 3	16000	32544	80	81
 4	16000	48792	80	81
+chr5	101	65041	80	81
+chr6	101	65193	80	81
+chr7	404	65345	80	81
+chr8	202	65804	80	81
```
Comment (droazen) [inline src/test/resources/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils/test.fasta.fai]: Still have a strange mix of "chr1" and "1" style contig names in this sequence dictionary -- all of these contigs should follow the same naming scheme.

File: src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java [hunk 17]
```diff
@@ -87,6 +88,11 @@ public static void validateDictionaries( final String name1,
             case IDENTICAL:
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java]: Remove interval arg

File: src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java [hunk 18]
```diff
@@ -126,25 +132,21 @@ public static void validateDictionaries( final String name1,
             }
 
             case DIFFERENT_INDICES: {
+
                 // This is currently only known to be problematic when the index mismatch is between a bam and the
                 // reference AND when the user's intervals actually include one or more of the contigs that are
                 // indexed differently from the reference. In this case, the engine will fail to correctly serve
                 // up the reads from those contigs, so throw an exception.
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java]: Comment needs updating

File: src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java [hunk 19]
```diff
@@ -126,25 +132,21 @@ public static void validateDictionaries( final String name1,
...
-                                        "the reference: %s.  As a result, the GATK engine will not correctly " +
-                                        "process reads from these contigs. You should either fix the sequence " +
-                                        "dictionaries for your reads so that these contigs have the same indices " +
-                                        "as in the sequence dictionary for your reference, or exclude these contigs " +
-                                        "from your intervals.";
-                        final UserException ex = new UserException.IncompatibleSequenceDictionaries(msg, name1, dict1, name2, dict2);
-                        throw ex;
-                    }
+                if ( isReadsToReferenceComparison ) {
+                    final String msg = "Some contigs included in the intervals to process have " +
```
Comment (droazen) [inline src/main/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils.java]: Error message should also be updated

File: src/test/java/org/broadinstitute/hellbender/engine/CRAMReferenceIntegrationTest.java [hunk 20]
```diff
@@ -70,7 +70,7 @@ public void testWrongRef(String fileIn, String extOut, String referenceFile) thr
                 "-R", reference.getAbsolutePath()
         };
         runCommandLine(args);
-    }*/
+    }
 
     @DataProvider(name="testingDataWrongRef")
     public Object[][] testingDataWrongRef() {
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/engine/CRAMReferenceIntegrationTest.java]: Name cramtest.fasta to make it clear that it's the wrong reference for cramtest.cram

File: src/test/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtilsUnitTest.java [hunk 21]
```diff
@@ -51,17 +51,16 @@
                 { Arrays.asList(CHR1_B37, CHR2_B37, CHR10_B37),    Arrays.asList(CHR1_B37, CHR2_B37, CHR10_B37),    IDENTICAL, null, false, null },
 
                 // Dictionaries with a common subset:
-                { Arrays.asList(CHR1_HG19),                                          Arrays.asList(CHR1_HG19, CHR_NONSTANDARD1),                                   COMMON_SUBSET, null, false, null },
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtilsUnitTest.java]: Think this first test case should be restored

File: src/test/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtilsUnitTest.java [hunk 22]
```diff
@@ -51,17 +51,16 @@
...
-                { Arrays.asList(CHR1_HG19, CHR2_HG19, CHR10_HG19, CHR_NONSTANDARD1), Arrays.asList(CHR1_HG19, CHR2_HG19, CHR10_HG19),                              COMMON_SUBSET, null, false, null },
-                { Arrays.asList(CHR1_HG19, CHR2_HG19, CHR10_HG19),                   Arrays.asList(CHR1_HG19, CHR2_HG19, CHR10_HG19, CHR_NONSTANDARD1),            COMMON_SUBSET, null, false, null },
                 { Arrays.asList(CHR_NONSTANDARD1, CHR1_HG19, CHR2_HG19, CHR10_HG19), Arrays.asList(CHR_NONSTANDARD2, CHR1_HG19, CHR2_HG19, CHR10_HG19),            COMMON_SUBSET, null, false, null },
                 { Arrays.asList(CHR_NONSTANDARD1, CHR1_HG19, CHR2_HG19, CHR10_HG19), Arrays.asList(CHR_NONSTANDARD2, CHR1_HG19, CHR2_HG19, CHR10_HG19, CHRM_HG19), COMMON_SUBSET, null, false, null },
                 { Arrays.asList(CHR1_B37, CHR2_B37, CHR10_B37, CHR_NONSTANDARD1),    Arrays.asList(CHR1_B37, CHR2_B37, CHR10_B37, CHR_NONSTANDARD2),               COMMON_SUBSET, null, false, null },
-                { Arrays.asList(CHR1_HG19, CHR2_HG19),                               Arrays.asList(CHR1_HG19, CHR2_HG19, CHR10_HG19),                              COMMON_SUBSET, null, false, null },
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtilsUnitTest.java]: Restore this test case too

File: src/test/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtilsUnitTest.java [hunk 23]
```diff
@@ -51,17 +51,16 @@
...
                 { Arrays.asList(CHR1_HG19, CHR_NONSTANDARD1),                        Arrays.asList(CHR1_HG19, CHR_NONSTANDARD2),                                   COMMON_SUBSET, null, false, null },
                 { Arrays.asList(CHR_NONSTANDARD1, CHR1_HG19),                        Arrays.asList(CHR_NONSTANDARD2, CHR1_HG19),                                   COMMON_SUBSET, null, false, null },
                 { Arrays.asList(CHR_NONSTANDARD1, CHR1_HG19),                        Arrays.asList(CHR_NONSTANDARD2, CHR1_HG19, CHRM_HG19),                        COMMON_SUBSET, null, false, null },
                 { Arrays.asList(CHR1_HG19, CHR2_HG19, CHR10_HG19, CHR_NONSTANDARD1), Arrays.asList(CHR1_HG19, CHR2_HG19, CHR10_HG19, CHR_NONSTANDARD2),            COMMON_SUBSET, null, false, null },
-                { Arrays.asList(CHR1_HG19, CHR2_HG19, CHR10_HG19, CHR_NONSTANDARD1), Arrays.asList(CHR1_HG19, CHR2_HG19, CHR10_HG19),                              COMMON_SUBSET, null, false, null },
-                { Arrays.asList(CHR1_HG19, CHR2_HG19, CHR10_HG19),                   Arrays.asList(CHR1_HG19, CHR2_HG19, CHR10_HG19, CHR_NONSTANDARD1),            COMMON_SUBSET, null, false, null },
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtilsUnitTest.java]: Restore 2nd test case here (can leave the 1st deleted)

File: src/test/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtilsUnitTest.java [hunk 24]
```diff
@@ -99,22 +101,28 @@
...
+                { Arrays.asList(CHR1_HG19, CHR2_HG19),                                                 Arrays.asList(CHRM_HG19, CHR_NONSTANDARD1, CHR1_HG19, CHR2_HG19),  DIFFERENT_INDICES, DIFFERENT_INDICES_EXCEPTION, true},
+                { Arrays.asList(CHR1_HG19, CHR2_HG19, CHR_NONSTANDARD1, CHRM_HG19 ),                   Arrays.asList(CHR1_HG19, CHR2_HG19, CHRM_HG19),                    DIFFERENT_INDICES, DIFFERENT_INDICES_EXCEPTION, true},
+                { Arrays.asList(CHR1_HG19, CHR2_HG19, CHR_NONSTANDARD1, CHRM_HG19, CHR_NONSTANDARD2 ), Arrays.asList(CHR1_HG19, CHR2_HG19, CHRM_HG19, CHR_NONSTANDARD2 ), DIFFERENT_INDICES, DIFFERENT_INDICES_EXCEPTION, true},
+                { Arrays.asList(CHR1_HG19, CHR_NONSTANDARD1, CHR2_HG19, CHRM_HG19, CHR_NONSTANDARD2 ), Arrays.asList(CHR1_HG19, CHR2_HG19, CHRM_HG19, CHR_NONSTANDARD2 ), DIFFERENT_INDICES, DIFFERENT_INDICES_EXCEPTION, true},
 
                 // These have isReadsToReferenceComparison == true but no overlapping intervals, so we don't expect an exception:
```
Comment (droazen) [inline src/test/java/org/broadinstitute/hellbender/utils/SequenceDictionaryUtilsUnitTest.java]: Comment is incorrect (we do expect an exception in these test cases)
